version: "3.9"
services:
    bot:
        build: .
        env_file:
            - .env
        init: true
        stop_signal: SIGINT
        restart: on-failure
        networks:
            - webnet
networks:
    webnet:
        name: happiness_webnet
        external: true
volumes:
    redis_data:

